<?xml version="1.0"?>
<robot name="kubot_robot"
	xmlns:xacro="https://ros.org/wiki/xacro">

	<xacro:include filename="$(find kubot_description)/urdf/kubot_properties.urdf.xacro" />

	<xacro:property name="base_mass" value="22.2" />
	<xacro:property name="base_radius" value="0.275" />
	<xacro:property name="base_length" value="0.320" />
	<xacro:property name="base_width" value="0.0" />

	<xacro:property name="wheel_mass" value="0.5" />
	<xacro:property name="wheel_radius" value="0.075" />
	<xacro:property name="wheel_length" value="0.050" />
	<xacro:property name="wheel_width" value="0.0" />
	<xacro:property name="wheel_joint_x" value="0.0" />
	<xacro:property name="wheel_joint_y" value="0.245" />
	<xacro:property name="wheel_joint_z" value="0.075" />

	<xacro:property name="caster_mass" value="0.05" />
	<xacro:property name="caster_radius" value="0.05" />
	<xacro:property name="caster_length" value="0.02" />
	<xacro:property name="caster_width" value="0.05" />
	<xacro:property name="caster_joint_x" value="0.25" />
	<xacro:property name="caster_joint_y" value="0.0" />
	<xacro:property name="caster_joint_z" value="0.025" />

	<xacro:macro name="base">
		<!-- Robot Frame  a.k.a base_link -->
		<link name="base_link">
			<visual>
				<origin xyz="-0.08 0 ${base_length/2+0.04}" rpy="0 0 0" />
				<geometry>
					<cylinder length="${base_length}" radius="${base_radius}" />
				</geometry>
				<xacro:material_yellow />
			</visual>

			<collision>
				<origin xyz="-0.08 0 ${base_length/2+0.04}" rpy="0 0 0" />
				<geometry>
					<cylinder length="${base_length}" radius="${base_radius}" />
				</geometry>
			</collision>

			<inertial>
				<origin xyz="-0.08 0 ${base_length/2+0.04}" rpy="0 0 0" />
				<xacro:cylinder_inertial_matrix m="${base_mass}" r="${base_radius}" h="${base_length}" />
			</inertial>
		</link>

		<!-- Right Wheel Frame-->
		<link name="wheel_right_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<mesh filename="package://kubot_description/meshes/robot_frame/$(arg model)/wheel_link.stl" scale="0.001 0.001 0.001" />
				</geometry>
				<xacro:material_black />
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
			</inertial>
		</link>

		<!-- Left Wheel Frame-->
		<link name="wheel_left_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<mesh filename="package://kubot_description/meshes/robot_frame/$(arg model)/wheel_link.stl" scale="0.001 0.001 0.001" />
				</geometry>
				<xacro:material_black />
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
			</inertial>
		</link>

		<!-- Rear Caster Frame -->
		<link name="rear_caster_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${caster_radius} ${caster_length} ${caster_width}" />
				</geometry>
				<xacro:material_white />
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${caster_radius} ${caster_length} ${caster_width}" />
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<xacro:sphere_inertial_matrix m="${caster_mass}" r="${caster_radius}" />
			</inertial>
		</link>

		<!-- Define Joint -->
		<joint name="wheel_right_joint" type="continuous">
			<parent link="base_link" />
			<child link="wheel_right_link" />
			<origin xyz="${wheel_joint_x} ${-1*wheel_joint_y} ${wheel_joint_z}" rpy="0 0 ${M_PI}" />
			<axis xyz="0 -1 0" />
		</joint>

		<joint name="wheel_left_joint" type="continuous">
			<parent link="base_link" />
			<child link="wheel_left_link" />
			<origin xyz="${wheel_joint_x} ${wheel_joint_y} ${wheel_joint_z}" rpy="0 0 0" />
			<axis xyz="0 1 0" />
		</joint>

		<joint name="rear_caster_joint" type="fixed">
			<origin xyz="${-1*caster_joint_x} ${caster_joint_y} ${caster_joint_z}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="rear_caster_link" />
		</joint>

		<!-- Define Gazebo -->
		<gazebo reference="base_link">
			<material>Gazebo/Orange</material>
		</gazebo>

		<gazebo reference="r1_frame">
			<material>Gazebo/Orange</material>
		</gazebo>

		<gazebo reference="logo_frame">
			<material>Gazebo/White</material>
		</gazebo>

		<gazebo reference="wheel_right_link">
			<mu1>100000</mu1>
			<mu2>100000</mu2>
			<kp>500000.0</kp>
			<kd>1.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>1.0</maxVel>
			<fdir1>0 1 0</fdir1>
			<material>Gazebo/Black</material>
		</gazebo>

		<gazebo reference="wheel_left_link">
			<mu1>100000</mu1>
			<mu2>100000</mu2>
			<kp>500000.0</kp>
			<kd>1.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>1.0</maxVel>
			<fdir1>0 1 0</fdir1>
			<material>Gazebo/Black</material>
		</gazebo>

		<gazebo reference="rear_caster_link">
			<mu1>0.1</mu1>
			<mu2>0.1</mu2>
			<kp>1000000.0</kp>
			<kd>100.0</kd>
			<minDepth>0</minDepth>
			<maxVel>0.01</maxVel>

			<material>Gazebo/Black</material>
		</gazebo>

		<gazebo>
			<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<commandTopic>cmd_vel</commandTopic>
				<odometryTopic>odom</odometryTopic>
				<odometryFrame>odom</odometryFrame>
				<odometrySource>world</odometrySource>
				<publishOdom>true</publishOdom>
				<publishOdomTF>true</publishOdomTF>
				<robotBaseFrame>footprint</robotBaseFrame>
				<publishWheelTF>false</publishWheelTF>
				<publishTf>true</publishTf>
				<publishWheelJointState>true</publishWheelJointState>
				<legacyMode>false</legacyMode>
				<updateRate>30</updateRate>
				<leftJoint>wheel_left_joint</leftJoint>
				<rightJoint>wheel_right_joint</rightJoint>
				<wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
				<wheelDiameter>${2*wheel_radius}</wheelDiameter>
				<wheelAcceleration>1</wheelAcceleration>
				<wheelTorque>10</wheelTorque>
				<rosDebugLevel>na</rosDebugLevel>
			</plugin>
		</gazebo>

	</xacro:macro>

	<!-- Lidar Frame a.k.a Lidar Pos-->
	<xacro:property name="lidar_joint_xyz" value="0.11 0 0.42" />
	<xacro:property name="lidar_joint_rpy" value="0 0 0" />

	<!-- Camera a.k.a Camera Pos -->
	<xacro:property name="camera_joint_xyz" value="0.1 0 0.14" />
	<xacro:property name="camera_joint_rpy" value="0 0 0" />

</robot>